### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by giulia-berto** [poldracklab/ds003-post-fMRIPrep-analysis#11]
Hi, I'm trying to run the first-level analysis through docker/singularity after having run fMRIPrep on sub-10 of this dataset. The command I am running is the following:
```
singularity run \
    -B `pwd`/bids:/bids \
    -B `pwd`/${derdir}:/derivatives_dir \
    -B `pwd`/${outdir}:/output \
    -B `pwd`/${workdir}:/work \
    docker://poldracklab/ds003-example:0.0.3 \
    /derivatives_dir /output participant \
    --participant-label $sub \
    --work-dir work \
    --bids-dir /bids \
    --space MNI152NLin2009cAsym 
```
where `output` and `work` are two empty directories that I created. However, I get the following error:
```
INFO:    Using cached SIF image
Failed to import duecredit due to No module named 'duecredit'
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.7/site-packages/nilearn/datasets/neurovault.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container
Traceback (most recent call last):
  File "/src/run.py", line 180, in <module>
    sys.exit(main())
  File "/src/run.py", line 153, in main
    suffix='events', return_type='file', **subquery)[0]
IndexError: list index out of range
```
Any suggestions on how to handle this? Thank you!

**Comment by giulia-berto** [comment]
duplicated
