### ISSUE TITLE
mask0 failed with the "wf_1st_level.susan_smooth.mask" 

### ISSUE THREAD

**Issue by liujiani0216** [poldracklab/ds003-post-fMRIPrep-analysis#14]
I have been using this code for the dataset mixed-gambles task. Then I got this error and do not know how to deal with it. Is there anyone who can help me with that. Thanks very much. It seems the command fslmaths generates a mask image but it is deleted automatically and raise errors.

220330-02:32:25,315 nipype.workflow INFO:
	 [Node] Setting-up "wf_1st_level.susan_smooth.mask" in "/users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask".
220330-02:32:25,319 nipype.workflow INFO:
	 [Node] Setting-up "_mask0" in "/users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0".
220330-02:32:25,323 nipype.workflow INFO:
	 [Node] Running "_mask0" ("nipype.interfaces.fsl.utils.ImageMaths"), a CommandLine Interface with command:
fslmaths /users/liujiani/data/openfmri/mixed/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz -mas /users/liujiani/data/openfmri/mixed/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz /Users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_mask.nii.gz

220330-02:32:44,25 nipype.workflow WARNING:
	 [Node] Error on "_mask0" (/users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0)
220330-02:32:44,26 nipype.workflow WARNING:
	 [Node] Error on "wf_1st_level.susan_smooth.mask" (/users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask)
220330-02:32:45,693 nipype.workflow ERROR:
	 Node mask.a0 failed to run on host liujianideMacBook-Pro.local.
220330-02:32:45,693 nipype.workflow ERROR:
	 Saving crash info to /Users/liujiani/OneDrive/fmri-post/mixed-post-fMRIPrep-analysis/crash-20220330-023245-liujiani-mask.a0-2ba7f255-5805-47ae-a9c4-e1999a7e9b1f.pklz
Traceback (most recent call last):
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 99, in nodelist_runner
    result = node.run(updatehash=updatehash)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 557, in _run_interface
    return self._run_command(execute)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 655, in _run_command
    _save_resultfile(result, outdir, self.name)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 301, in save_resultfile
    setattr(result.outputs, k, v)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 112, in validate
    self.info_text, value))
traits.trait_errors.TraitError: The trait 'out_file' of an ImageMathsOutputSpec instance is an existing file name, but the path  '/Users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_mask.nii.gz' does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 473, in run
    result = self._run_interface(execute=True)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1253, in _run_interface
    self.config['execution']['stop_on_first_crash'])))
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1128, in _collate_results
    for i, nresult, err in nodes:
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 106, in nodelist_runner
    if result.runtime and hasattr(result.runtime, 'traceback'):
AttributeError: 'NoneType' object has no attribute 'runtime'

220330-02:32:47,693 nipype.workflow ERROR:
	 could not run node: wf_1st_level.susan_smooth.mask.a0
Traceback (most recent call last):
  File "run.py", line 233, in <module>
    sys.exit(main())
  File "run.py", line 176, in main
    workflow.run(**plugin_settings)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 599, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/base.py", line 191, in run
    report_nodes_not_run(notrun)
  File "/Users/liujiani/opt/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by effigies** [comment]
There's a bug in nipype 1.7.0. Can you try `pip install "nipype<1.7"` and see what happens?

**Comment by liujiani0216** [comment]
Thanks. I have checked that the nipype installed version is 1.1.9. It is not nipype 1.7.0.

**Comment by liujiani0216** [comment]
Also it works fine for another dataset ds001. And I haved only revised the task contrast for mixed-gambles task in the workflow.py as follows. Then it raises the error.

  # l1_model creates a first-level model design
    l1_model = pe.Node(fsl.Level1Design(
        bases={'dgamma': {'derivs': True}},
        model_serial_correlations=True,
        contrasts=[('intask', 'T', ['task','parametric gain', 'parametric loss', 'distance from indifference'], [0, 0, -1, 0])],
        # orthogonalization=orthogonality,
    ), name='l1_model')

**Comment by effigies** [comment]
Okay, the error seems to be that a file that should have been created wasn't:

```
traits.trait_errors.TraitError: The trait 'out_file' of an ImageMathsOutputSpec instance is an existing file name, but the path '/Users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_mask.nii.gz' does not exist.
```

Can you verify that the file (`/Users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_mask.nii.gz`) does not exist? If it doesn't, let's try re-running the command:

```
fslmaths /users/liujiani/data/openfmri/mixed/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz \
    -mas /users/liujiani/data/openfmri/mixed/derivatives/sub-01/func/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz \
    /Users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_mask.nii.gz
```

Do you get an error message?

**Comment by liujiani0216** [comment]
No. I can run that command individually without any errors and generated the file /Users/liujiani/data/intermed/mixed/wf_1st_level/susan_smooth/_sub_01/mask/mapflow/_mask0/sub-01_task-mixedgamblestask_run-1_space-MNI152NLin2009cAsym_desc-preproc_bold_mask.nii.gz.

But if I run the workflow, then it does not create that file and raises errors.

**Comment by liujiani0216** [comment]
By the way, it seems that the function _bids2nipypeinfo in workflows need an "events.trial_type.values ". But for ds005, there is no trial type in the events file.
